import {
  AI_AUTHORING_ENDPOINTS,
  AI_AUTHORING_LIMITS,
  AI_AUTHORING_VERSION,
} from "@/lib/ai-contract";

export type AiInterfaceAudience = "agent" | "admin" | "cron";

export type AiInterfaceCatalogItem = {
  name: string;
  methods: string[];
  path: string;
  audience: AiInterfaceAudience;
  auth: string;
  feature: string;
  requestHint: string;
  responseHint: string;
};

export const aiInterfaceAudienceLabels: Record<AiInterfaceAudience, string> = {
  agent: "AI Agent",
  admin: "后台内部",
  cron: "定时任务",
};

export const aiInterfaceCatalog: AiInterfaceCatalogItem[] = [
  {
    name: "LLM 发现清单",
    methods: ["GET"],
    path: AI_AUTHORING_ENDPOINTS.llms,
    audience: "agent",
    auth: "公开",
    feature: "给 AI agent 快速识别写作接口、鉴权方式、约束和发现入口。",
    requestHint: "无需请求体。",
    responseHint: "text/plain，包含 OpenAPI、草稿写入、草稿回读和分类元数据入口。",
  },
  {
    name: "OpenAPI 规格",
    methods: ["GET"],
    path: AI_AUTHORING_ENDPOINTS.openapi,
    audience: "agent",
    auth: "公开",
    feature: "输出 AI 写作接口的 OpenAPI 3.1 描述，供 agent 自动生成调用计划。",
    requestHint: "无需请求体。",
    responseHint: "JSON OpenAPI 文档。",
  },
  {
    name: "站点分类与限制",
    methods: ["GET"],
    path: AI_AUTHORING_ENDPOINTS.meta,
    audience: "agent",
    auth: "Bearer AI Token，scope: taxonomy:read",
    feature: "读取分类、标签、标题长度、摘要长度、Markdown 和自动发布规则。",
    requestHint: "Authorization: Bearer <AI_TOKEN>。",
    responseHint: "success/data，包含 version、limits、categories、tags。",
  },
  {
    name: "写入或更新 AI 草稿",
    methods: ["POST"],
    path: AI_AUTHORING_ENDPOINTS.drafts,
    audience: "agent",
    auth: "Bearer AI Token，scope: drafts:write",
    feature: "按 externalId 幂等创建或更新 Markdown 草稿，并触发 AI 审稿；达标后可自动发布。",
    requestHint: "JSON: externalId、title、slug、content 必填；excerpt、coverImage、categorySlug、tagSlugs 可选。",
    responseHint: "success、operation、data、autoReview；201 表示创建，200 表示更新。",
  },
  {
    name: "读取 AI 草稿",
    methods: ["GET"],
    path: `${AI_AUTHORING_ENDPOINTS.drafts}/{externalId}`,
    audience: "agent",
    auth: "Bearer AI Token，scope: drafts:read",
    feature: "按外部草稿 ID 回读规范化后的文章草稿和发布状态。",
    requestHint: "externalId 必须是单段 path-safe 字符串，不能是 . 或 ..。",
    responseHint: "success/data，包含 postId、slug、content、readingTimeMinutes、published。",
  },
  {
    name: "AI 模型列表与新增",
    methods: ["GET", "POST"],
    path: "/api/admin/ai/models",
    audience: "admin",
    auth: "管理员会话",
    feature: "列出模型配置，或新增 OpenAI-compatible 模型。",
    requestHint: "POST 使用模型名称、baseUrl、requestPath、model、apiKey 与 capabilities。",
    responseHint: "success/data，返回脱敏后的模型选项。",
  },
  {
    name: "AI 模型更新与删除",
    methods: ["PATCH", "DELETE"],
    path: "/api/admin/ai/models/{id}",
    audience: "admin",
    auth: "管理员会话",
    feature: "更新数据库模型配置，或删除可删除模型。",
    requestHint: "PATCH 使用模型局部字段；DELETE 无请求体。",
    responseHint: "PATCH 返回更新后的模型；DELETE 返回 success。",
  },
  {
    name: "AI 模型连接测试",
    methods: ["POST"],
    path: "/api/admin/ai/models/{id}/test",
    audience: "admin",
    auth: "管理员会话",
    feature: "用当前模型配置发起真实连接测试并记录结果。",
    requestHint: "路径参数 id。",
    responseHint: "success/data.message 与 sample；失败时返回错误信息。",
  },
  {
    name: "默认 AI 模型切换",
    methods: ["POST"],
    path: "/api/admin/ai/models/default",
    audience: "admin",
    auth: "管理员会话",
    feature: "为 post-summary 或 cover-image 能力切换默认模型。",
    requestHint: "JSON: modelId、capability。",
    responseHint: "success/data，返回新的默认模型。",
  },
  {
    name: "单篇文章 AI 动作",
    methods: ["POST"],
    path: "/api/admin/ai/actions",
    audience: "admin",
    auth: "管理员会话",
    feature: "对已保存文章或当前编辑草稿执行摘要、SEO、标题、Slug、标签、分类等单篇 AI 动作，并进入任务中心。",
    requestHint: "JSON: postId 或 draft、action、modelId 可选；同时传 postId 和 draft 时使用当前表单内容但绑定已保存文章。",
    responseHint: "success/data，包含 taskId、itemId、action、modelId、durationMs、output；output._meta 含模型、耗时、promptVersion 与可选质量检查。",
  },
  {
    name: "应用 AI 建议",
    methods: ["POST"],
    path: "/api/admin/ai/actions/apply",
    audience: "admin",
    auth: "管理员会话",
    feature: "把已完成任务项的 AI 建议写回文章。",
    requestHint: "JSON: itemId。",
    responseHint: "success/data，返回更新后的文章。",
  },
  {
    name: "一键文章信息生成",
    methods: ["POST"],
    path: "/api/admin/ai/actions/article-info",
    audience: "admin",
    auth: "管理员会话",
    feature: "创建文章信息 AI 任务，生成 slug、摘要、SEO 描述、分类和标签建议；只回填编辑器表单，不直接落库。",
    requestHint: "JSON: postId 或 draft，modelId 可选；保留标题和正文。",
    responseHint: "success/data，包含 taskId、articleInfo、quality 与任务项输出；部分失败时 502 仍返回 partial、failures、quality 与成功 items 供前端预览确认。",
  },
  {
    name: "批量 AI 任务",
    methods: ["GET", "POST"],
    path: "/api/admin/ai/batch",
    audience: "admin",
    auth: "管理员会话",
    feature: "创建批量文章 AI 补全任务，或恢复执行中的批量任务。",
    requestHint: "POST: postIds、actions、mode、apply、modelId；GET 可带 resume=1 与 taskId。",
    responseHint: "POST 返回 202 任务；GET 返回 success。",
  },
  {
    name: "AI 任务列表",
    methods: ["GET"],
    path: "/api/admin/ai/tasks",
    audience: "admin",
    auth: "管理员会话",
    feature: "分页查询摘要、单篇动作和批量补全任务。",
    requestHint: "Query: page、limit、status、type。",
    responseHint: "success/data，包含 tasks 与 pagination。",
  },
  {
    name: "AI 任务详情",
    methods: ["GET"],
    path: "/api/admin/ai/tasks/{id}",
    audience: "admin",
    auth: "管理员会话",
    feature: "查看单个 AI 任务的状态、任务项、输入快照和输出。",
    requestHint: "路径参数 id。",
    responseHint: "success/data，返回任务详情。",
  },
  {
    name: "AI 失败项重试",
    methods: ["POST"],
    path: "/api/admin/ai/tasks/{id}/retry",
    audience: "admin",
    auth: "管理员会话",
    feature: "复制失败任务项并重新排队运行。",
    requestHint: "路径参数 id。",
    responseHint: "202 success/data，返回重试任务。",
  },
  {
    name: "文章摘要生成",
    methods: ["POST"],
    path: "/api/admin/posts/summarize",
    audience: "admin",
    auth: "管理员会话",
    feature: "为当前文章内容生成一段摘要。",
    requestHint: "JSON: content 必填，title、modelId 可选。",
    responseHint: "success/data.summary 与 modelId。",
  },
  {
    name: "批量文章摘要",
    methods: ["GET", "POST"],
    path: "/api/admin/posts/summarize/bulk",
    audience: "admin",
    auth: "管理员会话",
    feature: "创建批量摘要任务，或查询/恢复摘要任务快照。",
    requestHint: "POST: ids、modelId；GET: jobId、resume=1。",
    responseHint: "POST 返回 202 任务；GET 返回任务快照。",
  },
  {
    name: "文章 AI 审稿",
    methods: ["POST"],
    path: "/api/admin/posts/review",
    audience: "admin",
    auth: "管理员会话",
    feature: "对当前编辑内容生成结构化发布意见，不直接改变发布状态。",
    requestHint: "JSON: title、slug、content、coverImage。",
    responseHint: "success/data，包含 verdict、score、summary 和检查项。",
  },
  {
    name: "文章元信息补全",
    methods: ["POST"],
    path: "/api/admin/posts/metadata",
    audience: "admin",
    auth: "管理员会话",
    feature: "旧版文章元信息补全兼容入口；编辑器单项 AI 按钮已迁移到 /api/admin/ai/actions。",
    requestHint: "JSON: content，title 可选，field 可为 all/title/slug/category/tags。",
    responseHint: "success/data，按 field 返回对应元信息；不创建任务中心记录，后续仅作为兼容层保留。",
  },
  {
    name: "AI 封面生成",
    methods: ["POST"],
    path: "/api/admin/covers/generate",
    audience: "admin",
    auth: "管理员会话 + 生图限流",
    feature: "根据标题、正文、摘要或提示词生成封面并保存到媒体库。",
    requestHint: "JSON: title、excerpt、content、prompt、modelId、size。",
    responseHint: "success/data，返回封面资源。",
  },
  {
    name: "AI 日报运行",
    methods: ["GET", "POST"],
    path: "/api/admin/ai-news/run",
    audience: "admin",
    auth: "管理员会话",
    feature: "手动生成/重生成 AI 日报，或读取最近运行记录。",
    requestHint: "POST: date、modelId、regenerate；GET 无请求体。",
    responseHint: "POST 返回生成结果；GET 返回最近 20 条运行记录。",
  },
  {
    name: "AI 日报候选明细",
    methods: ["GET"],
    path: "/api/admin/ai-news/candidates",
    audience: "admin",
    auth: "管理员会话",
    feature: "查看一次 AI 日报运行的候选新闻、AI 评分、标签和引用数。",
    requestHint: "Query: runId 必填，selectedOnly 可选。",
    responseHint: "success/data，返回候选新闻列表。",
  },
  {
    name: "AI 日报定时入口",
    methods: ["GET", "POST"],
    path: "/api/cron/ai-news",
    audience: "cron",
    auth: "Bearer AI_NEWS_CRON_SECRET",
    feature: "给定时任务触发 AI 日报后台队列，并查询队列运行状态。",
    requestHint: "POST Query: date、regenerate 可选；GET Query: date、after 可选。",
    responseHint: "POST 返回 202 queued；GET 返回 202 pending/running、200 finished，失败运行返回 500。",
  },
];

export function buildAiAgentUsagePrompt({
  baseUrl,
  siteName,
}: {
  baseUrl: string;
  siteName: string;
}) {
  const normalizedBaseUrl = baseUrl.replace(/\/+$/, "");

  return [
    `你是 ${siteName} 的 AI 写作 agent。你可以通过 HTTP API 创建或更新博客草稿。`,
    "",
    "工作流程：",
    `1. 先读取 ${normalizedBaseUrl}${AI_AUTHORING_ENDPOINTS.llms} 和 ${normalizedBaseUrl}${AI_AUTHORING_ENDPOINTS.openapi}，确认接口版本 ${AI_AUTHORING_VERSION}、字段、错误码和约束。`,
    `2. 使用 Authorization: Bearer <AI_TOKEN> 请求 ${normalizedBaseUrl}${AI_AUTHORING_ENDPOINTS.meta}，读取当前分类、标签和 limits。`,
    `3. 写文章时生成 Markdown 正文，并保证 title 不超过 ${AI_AUTHORING_LIMITS.titleMaxLength} 字，excerpt 不超过 ${AI_AUTHORING_LIMITS.excerptMaxLength} 字。`,
    "4. externalId 使用稳定、可重复的单段 ID，例如任务 ID 或 slug；slug 使用英文小写、数字和连字符。",
    `5. 调用 POST ${normalizedBaseUrl}${AI_AUTHORING_ENDPOINTS.drafts}，只提交可解析 JSON，不要把说明文字混进请求体。`,
    `6. 写入后调用 GET ${normalizedBaseUrl}${AI_AUTHORING_ENDPOINTS.drafts}/{externalId} 回读结果，确认 published 和 autoReview 状态。`,
    "7. 如果 autoReview verdict 为 needs-work 或 published 为 false，根据审稿摘要修订后用同一个 externalId 再次 POST。",
    "",
    "POST JSON 模板：",
    JSON.stringify(
      {
        externalId: "agent-task-001",
        title: "文章标题",
        slug: "article-slug",
        content: "# Markdown 正文\\n\\n从这里开始写文章。",
        excerpt: "70 到 120 个中文字符的摘要。",
        categorySlug: "从 /api/ai/meta 返回的分类 slug 中选择",
        tagSlugs: ["从 /api/ai/meta 返回的标签 slug 中选择"],
      },
      null,
      2,
    ),
  ].join("\n");
}
